{
 "title": "QAxe+ Miner",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "network", "query": "mainnet,testnet,regtest" }
  ]
 },
 "panels": [
  {
   "title": "Hash Rate GH/s",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "GHs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"piaxe\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${network}_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"hashing_speed\")\n  |> last()  \n"
    }
   ]
  },
  {
   "title": "Total Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"piaxe\")\n  |> range(start: -1y)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${network}_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_uptime\")\n  |> last()\n  |> map(fn: (r) => {\n      uptime_seconds = r._value\n      days = uptime_seconds / 86400\n      hours = (uptime_seconds % 86400) / 3600\n      minutes = (uptime_seconds % 3600) / 60\n      uptime_formatted = \"${days}d ${hours}h ${minutes}m\"\n      return ({_time: r._time, _value: uptime_formatted})\n  })"
    }
   ]
  },
  {
   "title": "Session ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"piaxe\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${network}_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime\")\n  |> last()  \n  |> map(fn: (r) => {\n      uptime_seconds = r._value\n      days = uptime_seconds / 86400\n      hours = (uptime_seconds % 86400) / 3600\n      minutes = (uptime_seconds % 3600) / 60\n      uptime_formatted = \"${days}d ${hours}h ${minutes}m\"\n      return ({_field: \"Uptime\", _time: r._time, _value: uptime_formatted})\n  })\n"
    },
    {
     "query": "import \"math\"\nfrom(bucket: \"piaxe\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${network}_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"best_difficulty\")\n  |> last()  \n  |> map(fn: (r) => {\n      suffix = if r._value >= 1000000000000.0 then \"T\"\n               else if r._value >= 1000000000.0 then \"G\"\n               else if r._value >= 1000000.0 then \"M\"\n               else if r._value >= 1000.0 then \"k\"\n               else \"\"    \n      scaled = if r._value >= 1000000000000.0 then r._value / 1000000000000.0\n                else if r._value >= 1000000000.0 then r._value / 1000000000.0\n                else if r._value >= 1000000.0 then r._value / 1000000.0\n                else if r._value >= 1000.0 then r._value / 1000.0\n                else r._value\n      \n      number = math.trunc(x: scaled * 100.0) / 100.0\n      return ({\n        _time: r._time, \n        _field: \"Best Difficulty\",\n        _value: string(v: number) + suffix\n      })\n  })\n"
    },
    {
     "query": "from(bucket: \"piaxe\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${network}_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"accepted\")\n  |> last()  \n  "
    },
    {
     "query": "from(bucket: \"piaxe\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${network}_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"not_accepted\")\n  |> last()  \n  "
    },
    {
     "query": "from(bucket: \"piaxe\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${network}_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pool_errors\")\n  |> last()  \n  \n\n\n  "
    },
    {
     "query": "from(bucket: \"piaxe\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${network}_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"duplicate_hashes\")\n  |> last()  \n  \n\n\n  "
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"piaxe\")\n  |> range(start: -5m)  // Adjust the time range as needed\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${network}_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> last()  \n  "
    }
   ]
  },
  {
   "title": "Power W",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"piaxe\")\n  |> range(start: -5m)  // Adjust the time range as needed\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${network}_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"power\")\n  |> last()  \n  "
    }
   ]
  },
  {
   "title": "Efficienty GH/W",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "GH/W" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "// Define the time range and bucket\ntimeRange = -5m\nbucketName = \"piaxe\"\n\n// Query and aggregate power from the smart plug data\npower = from(bucket: bucketName)\n  |> range(start: timeRange)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${network}_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"power\")\n  |> aggregateWindow(every: 1m, fn: last)  // Adjust 'every' to match your data frequency\n\n// Query and aggregate hashing speed from the network stats data\nhashingSpeed = from(bucket: bucketName)\n  |> range(start: timeRange)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${network}_stats\")  // Adjust your measurement name\n  |> filter(fn: (r) => r[\"_field\"] == \"hashing_speed\")\n  |> aggregateWindow(every: 1m, fn: last)  // Use the same 'every' as used for power\n\n// Join the two streams on the time columns\njoinedData = join(\n  tables: {power: power, hashingSpeed: hashingSpeed},\n  on: [\"_start\", \"_stop\", \"_time\"],  // Join on window start, stop, and time\n  method: \"inner\"\n)\n\n// Calculate the ratio of hashing speed to power\nresult = joinedData\n  |> map(fn: (r) => ({\n      _time: r._time,\n      ratio: r._value_hashingSpeed / r._value_power\n    })\n  )\n\n// Output the result\nresult\n"
    }
   ]
  },
  {
   "title": "Total Best Difficulty",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"math\"\nfrom(bucket: \"piaxe\")\n  |> range(start: -1y)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${network}_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_best_difficulty\")\n  |> last()  \n  |> map(fn: (r) => {\n      suffix = if r._value >= 1000000000000.0 then \"T\"\n               else if r._value >= 1000000000.0 then \"G\"\n               else if r._value >= 1000000.0 then \"M\"\n               else if r._value >= 1000.0 then \"k\"\n               else \"\"    \n      scaled = if r._value >= 1000000000000.0 then r._value / 1000000000000.0\n                else if r._value >= 1000000000.0 then r._value / 1000000000.0\n                else if r._value >= 1000000.0 then r._value / 1000000.0\n                else if r._value >= 1000.0 then r._value / 1000.0\n                else r._value\n      \n      number = math.trunc(x: scaled * 100.0) / 100.0\n      return ({\n        _time: r._time, \n        _value: string(v: number) + suffix\n      })\n  })\n"
    }
   ]
  },
  {
   "title": "Total Blocks Found",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"piaxe\")\n  |> range(start: -1y)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${network}_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_blocks_found\")\n  |> last()  \n  |> map(fn: (r) => {\n      return ({_field: r._field, _time: r._time, _value: string(v: r._value)})\n  })\n"
    }
   ]
  },
  {
   "title": "Hash Rate GH/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"piaxe\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${network}_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"hashing_speed\")\n  |> aggregateWindow(every: 5s, fn: mean) \n"
    },
    {
     "query": "from(bucket: \"piaxe\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${network}_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"hashing_speed\")\n  |> aggregateWindow(every: 25m, fn: mean) \n"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"piaxe\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${network}_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n|> aggregateWindow(every: 1m, fn: mean) "
    },
    {
     "query": "from(bucket: \"piaxe\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${network}_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature2\")\n|> aggregateWindow(every: 1m, fn: mean) "
    }
   ]
  },
  {
   "title": "Efficiency GH/W",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 14, "y": 8 },
   "targets": [
    {
     "query": "// Define the time range and bucket\ntimeRange = v.timeRangeStart\nbucketName = \"piaxe\"\n\n// Query for power and hashing speed, and calculate the ratio\npowerQuery = from(bucket: bucketName)\n  |> range(start: timeRange)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${network}_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"power\")\n  |> aggregateWindow(every: 1m, fn: last, createEmpty: false)  // Generate consistent data points over time\n\nhashingSpeedQuery = from(bucket: bucketName)\n  |> range(start: timeRange)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${network}_stats\")  // Adjust your measurement name\n  |> filter(fn: (r) => r[\"_field\"] == \"hashing_speed\")\n  |> aggregateWindow(every: 1m, fn: last, createEmpty: false)\n\n// Calculate ratio and map it\nresult = join(\n  tables: {power: powerQuery, hashingSpeed: hashingSpeedQuery},\n  on: [\"_time\"],\n  method: \"inner\"\n)\n  |> map(fn: (r) => ({\n      _time: r._time,\n      ratio: r._value_hashingSpeed / r._value_power\n    })\n  )\n\n// Output the result for visualization\nresult\n"
    },
    {
     "query": "// Define the time range and bucket\ntimeRange = v.timeRangeStart\nbucketName = \"piaxe\"\n\n// Query for power and hashing speed, and calculate the ratio\npowerQuery = from(bucket: bucketName)\n  |> range(start: timeRange)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${network}_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"power\")\n  |> aggregateWindow(every: 1m, fn: last, createEmpty: false)  // Generate consistent data points over time\n\nhashingSpeedQuery = from(bucket: bucketName)\n  |> range(start: timeRange)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${network}_stats\")  // Adjust your measurement name\n  |> filter(fn: (r) => r[\"_field\"] == \"hashing_speed\")\n  |> aggregateWindow(every: 1m, fn: last, createEmpty: false)\n\n// Calculate ratio and map it\nresult = join(\n  tables: {power: powerQuery, hashingSpeed: hashingSpeedQuery},\n  on: [\"_time\"],\n  method: \"inner\"\n)\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r._value_hashingSpeed / r._value_power\n    })\n  )\n  |> aggregateWindow(every: 25m, fn: mean)\n\n// Output the result for visualization\nresult\n"
    }
   ]
  },
  {
   "title": "Pool Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"piaxe\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${network}_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pool_errors\")\n  |> difference()\n  "
    }
   ]
  },
  {
   "title": "Asic Temp [°C]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"piaxe\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${network}_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"asic_temp1\")\n  |> aggregateWindow(every: 1m, fn: mean) \n  "
    },
    {
     "query": "from(bucket: \"piaxe\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${network}_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"asic_temp2\")\n|> aggregateWindow(every: 1m, fn: mean) \n"
    },
    {
     "query": "from(bucket: \"piaxe\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${network}_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"asic_temp3\")\n|> aggregateWindow(every: 1m, fn: mean) \n"
    },
    {
     "query": "from(bucket: \"piaxe\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${network}_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"asic_temp4\")\n|> aggregateWindow(every: 1m, fn: mean) \n"
    }
   ]
  },
  {
   "title": "Power W",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 14, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"piaxe\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${network}_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"power\")\n  |> aggregateWindow(every: 5s, fn: mean) \n"
    }
   ]
  }
 ]
}